name: Habit Tracker App CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main


jobs:
  flutter_build:
   name: Run flutter build
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with:
        java-version: "12.x"
     - uses: subosito/flutter-action@v2.6.1

     - run: flutter pub get

     - run: flutter clean

     - run: flutter build apk --release

     - uses: actions/upload-artifact@v1
       with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
